### PR TITLE
Add options to export image preview directly

### PR DESCRIPTION
**Pull request by Krasjet**
This pull request adds two options `--input` and `--output` so that you can export an image preview of a font file. A description on how you can setup file preview for fonts in `vifm` will come later.

### CODE REVIEW

**Comment by Krasjet** [comment]
Example:
```bash
fontpreview --i font.otf --o preview.png
```

**Comment by Krasjet** [comment]
There is a bug currently that breaks the normal functionality of the script. I'm currently working on it.

**Comment by Krasjet** [comment]
The vifm setup instructions can be found [here](https://krasjet.com/scribbles/font-preview.html) :)

**Comment by sdushantha** [comment]
@Krasjet Thank you for the detailed instructions about `vifm`!
Could you please add what `-o` and `-i` means to the `show_help` function?

**Comment by Krasjet** [comment]
Documentations are added. I also fixed a typo in `--version`.

**Comment by sdushantha** [comment]
image
Could you please fix that minor thing? Once you have done that, I will merge it :)

**Comment by Krasjet** [comment]
Oh, this is because short arguments have only one character, so there's no comma between them. The `h` option doesn't take any arguments so it's followed directly by `i`

**Comment by Krasjet** [comment]
By the way, I think you might forget to submit the review because I can't see it.

**Comment by sdushantha** [comment]
> Oh, this is because short arguments have only one character, so there's no comma between them. The h option doesn't take any arguments so it's followed directly by i

I did not know that, I guess I learned something new today! :blush: 

> By the way, I think you might forget to submit the review because I can't see it.

Sorry about that, my bad :sweat_smile:

**Comment by sdushantha** [comment]
Quick question, could I have your config for `vifm`? Your setup looks so clean. Im thinking of moving from `ranger` to `vifm` because `ranger` is kinda slow, sometimes freezes and the keybindings dont always work. :disappointed:

**Comment by Krasjet** [comment]
I haven't played with vifm's config too much, most of them are from the default config files. Probably the only interesting ones are the fileviewer settings: https://gist.github.com/Krasjet/44b3d3b5732384423443b540813aa458

**Comment by sdushantha** [comment]
@Krasjet Thank you so much!
Do you know why the images are not getting a preview? I put `vifmimg` in the `scripts` dir like it is supposed to be, but nothing is happening

shot_20-02-15_at_08-20-47

**Comment by Krasjet** [comment]
I'm not exactly sure, maybe you could try to add the scripts directory to path. You can also add some echo statements in the scripts to see if it's executed properly.

**Comment by Krasjet** [comment]
Oh, by the way, you need to run vifm using the `vifmrun` wrapper script described [here](https://krasjet.com/scribbles/font-preview.html)

**Comment by sdushantha** [comment]
@Krasjet Thank you, it works like a charm now!

**Comment by sdushantha** [comment]
I got album cover for audio files to work now!
https://github.com/sdushantha/dotfiles/blob/master/vifm/.config/vifm/scripts/vifmimg
image

**Pull request merged**
